replicaCount: 1

image:
  repository: <account-id>.dkr.ecr.<region>.amazonaws.com/shopnow/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  nodePort: 30500

config:
  MONGODB_HOST: mongo
  MONGODB_PORT: "27017"
  APP_ENV: "k8s-demo"

secret:
  enabled: true
  mongodb:
    user: shopuser
    password: ShopNowPass123

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
