apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admin.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin.fullname" . }}
    spec:
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            {{- if .Values.nginx.enableConfigMap }}
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            {{- end }}
      volumes:
        {{- if .Values.nginx.enableConfigMap }}
        - name: nginx-conf
          configMap:
            name: {{ include "admin.fullname" . }}-nginx
        {{- end }}
