replicaCount: 1

image:
  repository: <account-id>.dkr.ecr.<region>.amazonaws.com/shopnow/admin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  nodePort: 30081

nginx:
  enableConfigMap: true
  config: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      location / { try_files $uri $uri/ /index.html; }
      location /admin/ { proxy_pass http://backend:5000/admin/; }
      location = /health { return 200 'OK'; add_header Content-Type text/plain; }
    }

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  path: /admin/(.*)
  pathType: ImplementationSpecific
  host: ""                      # optional host; leave blank for path-only routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  ingressClassName: nginx
