apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headlessName }}
spec:
  clusterIP: None
  selector:
    app: {{ include "mongo.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
