apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-nginx-conf
  namespace: shopnow-demo
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      
      # Serve admin app from /admin path (built with PUBLIC_URL=/admin)
      location /admin {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /admin/index.html;
        
        # Handle static assets within /admin
        location ~* /admin/.*\.(css|js|map|svg|gif|png|jpg|jpeg|ico|woff2?|ttf|eot)$ {
          expires 30d;
          add_header Cache-Control "public, immutable";
          try_files $uri =404;
        }
      }
      
      # Admin API - proxy to backend
      location /admin/api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90;
      }
      
      # Health check
      location = /health {
        return 200 'OK';
        add_header Content-Type text/plain;
      }
      
      # Redirect root to admin
      location = / {
        return 301 /admin/;
      }
      
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options DENY;
    }