replicaCount: 2

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

service:
  port: 27017
  headlessName: mongo-headless

stateful:
  volume:
    storageClassName: gp3-ssd
    storage: 5Gi

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
