apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: shopnow-demo
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      location /aryan { 
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /aryan/index.html;
      }

      location /aryan/api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
      }
      location = /health { return 200 'OK'; add_header Content-Type text/plain; }
    }

