replicaCount: 2

image:
  repository: <account-id>.dkr.ecr.<region>.amazonaws.com/shopnow/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # ClusterIP | NodePort | LoadBalancer
  port: 80
  nodePort: 30080  # only used if NodePort

nginx:
  enableConfigMap: true
  config: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      location / { try_files $uri $uri/ /index.html; }
      location /api/ { proxy_pass http://backend:5000/; }
      location = /health { return 200 'OK'; add_header Content-Type text/plain; }
    }

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  path: /health
  port: 80
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  path: /(.*) 
  pathType: ImplementationSpecific
  host: ""                      # optional host; leave blank for path-only routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  ingressClassName: nginx
