{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
type: Opaque
stringData:
  mongodb_user: "{{ .Values.secret.mongodb.user }}"
  mongodb_password: "{{ .Values.secret.mongodb.password }}"
{{- end }}
